version: '3.8'

services:
  evouliton-test-back:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testproj
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data